# j-hc/revanced-magisk-module configuration

upstream = "revanced-extended"

# Modo exclusivo: desativa tudo por padrão para deixar o app original
include_only = ["video-ads", "background-play"]

# Mantém as listas padrão limpas
exclude = []
include = []

lang = "en"
