enable-module-update = true
parallel-jobs = 1

[YouTube]
enabled = true
build-mode = "module"
upstream = "revanced"
version = "auto"
excluded-patches = []
included-patches = ["'Video ads'", "'Background play'"]
